### ISSUE TITLE
Problem running the code

### ISSUE THREAD

**Issue by akalasxinos** [UoA-eResearch/populartimes#2]
Hello!

I am trying to reproduce the code with only the first 2 locations ( in order to test that is working and then make a new custom locations file). I get the following errors:

Traceback (most recent call last):

  File "C:\Users\vader\Downloads\populartimes-main\populartimes-main\util.py", line 139, in extract_page
    places = refreshPlaces(driver)

  File "C:\Users\vader\Downloads\populartimes-main\populartimes-main\util.py", line 124, in refreshPlaces
    driver.execute_script("arguments[0].scrollTo(0, arguments[0].scrollHeight)", driver.find_element_by_css_selector("div[aria-label^='Results for']"))

  File "C:\Users\vader\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 814, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)

  File "C:\Users\vader\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1251, in find_element
    return self.execute(Command.FIND_ELEMENT, {

  File "C:\Users\vader\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)

  File "C:\Users\vader\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)

NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"div[aria-label^='Results for']"}
  (Session info: headless chrome=102.0.5005.63)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\vader\Downloads\populartimes-main\populartimes-main\scrape.py", line 25, in <module>
    extract_page(driver, features)

  File "C:\Users\vader\Downloads\populartimes-main\populartimes-main\util.py", line 173, in extract_page
    raise IndexError

IndexError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\vader\Downloads\populartimes-main\populartimes-main\scrape.py", line 42, in <module>
    location = next(locations)

StopIteration

**Comment by neon-ninja** [comment]
Hi!

`StopIteration` being raised on `locations` means you're done - the scraper ran out of locations to check. Is there data in `data.geojson`?

https://github.com/UoA-eResearch/populartimes/commit/882d3b238303456c62692f67aaeb9805eb94dea1 should handle this Exception correctly

**Comment by akalasxinos** [comment]
Thank you @neon-ninja . I think that my problem is that when i test with a custom locations.csv (for example Paris, France) no data.geojson is saved. It is like it can not find anything. Even with a data.geojson with 1 feature, after searching for custom locations the final file contains still 1 feature and "Clicking on Tourism France Louvre
Has popular times" does not appear.

**Comment by neon-ninja** [comment]
Huh? Can you post the output from when you run scrape.py?

**Comment by akalasxinos** [comment]
Have 1 locations
  0%|          | 0/1 [00:00<?, ?it/s]
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 102.0.5005
[WDM] - Get LATEST chromedriver version for 102.0.5005 google-chrome
[WDM] - Driver [C:\Users\vader\.wdm\drivers\chromedriver\win32\102.0.5005.61\chromedriver.exe] found in cache
place of interest in Paris, France

  0%|          | 0/20 [00:00<?, ?it/s]scrolling
  0%|          | 0/20 [00:10<?, ?it/s]
100%|██████████| 1/1 [00:16<00:00, 16.61s/it]All done!
All locations complete

and no data.geojson created,     features dict is empty

**Comment by neon-ninja** [comment]
I wrote the code for the English version of Google Maps, it won't work with other languages. Try set your language to English

**Comment by akalasxinos** [comment]
Thank you for your responses, I am using English version all along.

**Comment by neon-ninja** [comment]
I also wrote it for the non-logged in version of Google Maps, maybe try log out of your google account. Also please upload a screenshot of what your google maps search results look like, and also the html

**Comment by neon-ninja** [comment]
I've pushed two possible fixes - https://github.com/UoA-eResearch/populartimes/commit/f63c8c51bda28943a9edf05a10bad40dcc14f80f and https://github.com/UoA-eResearch/populartimes/commit/a3ad16aff333b3071bb786712bc1bfda560fcb73 - try latest master branch and see if they helped

**Comment by akalasxinos** [comment]
Now it is working perfectly. Thank you very much!!!
