### ISSUE TITLE
Live Information Not Showing In My Output

### ISSUE THREAD

**Issue by kasturimw** [UoA-eResearch/populartimes#3]
Hi Nick,

Thank you for making this great script!

I already run the scripts and I got all the information like latitude and longitude, average popular time, and other but for the live_info, it's showing zero output even though in google map, the location has live popular time. 

I'd be very appreciative if you could advise me on this issue. 

Thank you.

**Comment by kasturimw** [comment]
![image](https://user-images.githubusercontent.com/100817952/174215271-a6902ac2-cdb2-43b8-b56e-dbe10e4c089e.png)

This is the picture.

**Comment by neon-ninja** [comment]
Hi @kasturimw - https://github.com/UoA-eResearch/populartimes/commit/14dfa207ff6ce9d1a817299ce95522a7df0942b7 should fix this issue, both for the initial scrape using `./scrape.py` and updating existing data with `./update_populartimes_data.py`. Please give it a try and see how you go

**Comment by kasturimw** [comment]
Hi Nick!

Now, it is working perfectly. 

Thank you for your efforts!

![image](https://user-images.githubusercontent.com/100817952/176078020-6fa546ad-9e8b-41c1-acc0-1be0906ff138.png)
