### ISSUE TITLE
Driver Problem

### ISSUE THREAD

**Issue by PaolaAlbino** [UoA-eResearch/populartimes#4]
Hi!

I am trying to reproduce the code with only 1 location but I get 2 kind of errors : 

ERROR: 'WebDriver' object has no attribute 'find_element_by_css_selector' 

Exception has occurred: UnicodeEncodeError
'charmap' codec can't encode character '\u22c5' in position 305377: character maps to <undefined>

**Comment by neon-ninja** [comment]
What location are you having this problem with?

**Comment by PaolaAlbino** [comment]
I already figured this one out, but now i'm having problem with this part 
 ERROR: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[aria-label='Next page']"}████████████████████████████████████| 20/20 [00:47<00:00,  2.17s/it]
  (Session info: headless chrome=105.0.5195.102)

I changed the code to a new version of Selenium cause of the new CSS Selector. The code run some adresses but then stop and show me this error, and below this one:

Traceback (most recent call last):
  File "f:\Codigo Google Popular Times\populartimes-main\populartimes-main\scrape.py", line 26, in <module>
    if driver.find_element(By.CSS_SELECTOR, "[aria-label='Next page']").get_attribute("disabled"):
  File "C:\Users\ppalb\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 857, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\ppalb\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ppalb\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[aria-label='Next page']"}
  (Session info: headless chrome=105.0.5195.102)

**Comment by neon-ninja** [comment]
It looks like Google Maps has been updated. There's no longer a "Next Page" button, it just scrolls until you get a "You've reached the end of the list." message

**Comment by neon-ninja** [comment]
I think https://github.com/UoA-eResearch/populartimes/commit/3c516d38c073a6a05243ae8e5eb3d8d84e6e28f2 should fix this, give it a try and let me know how you go

**Comment by neon-ninja** [comment]
Oh, and also https://github.com/UoA-eResearch/populartimes/commit/5493fc8ebf596f2abf9ab7c82292822bcfe2f100 for the compatibility issue with Selenium 4.3.0 you mentioned

**Comment by PaolaAlbino** [comment]
That worked thanks. I just had to change the "pd.read_csv("locations.csv")" to the path of locations.csv, and add "utf-8".
